[Remove] 퇴사자 상세 페이지 링크 삭제
PLAIF-dev/.github pull request #30
Opened 2023-10-04 09:42 UTC by youngmin-gwon

## 내용

> 마지막 PR 이 되겠군요. 근무하는 동안 함께 즐겁게 일할 수 있어서 좋았습니다. 떠난 이후에도 이 기분을 쉽게 잊긴 힘들거 같습니다.

해당 PR 의 내용은 다음과 같습니다.
- 퇴사자(권영민/software) 상세페이지 링크 삭제하고 dashed-line 으로 변경
  - 상세 페이지를 삭제하진 않음

## 추가

![Screenshot 2023-10-04 at 6 40 03 PM](https://github.com/PLAIF-dev/.github/assets/52237605/7e6a02b3-ac78-4a98-a68e-f50475ea15bd)

2023-10-04 09:44 UTC, youngmin-gwon commented
@powerstrong

승인 모두 거친 이후 merge 만 부탁드리겠습니다 😄 

@PLAIF-dev/vision , @PLAIF-dev/motion , @PLAIF-dev/software 
모두 감사했어요~~~~~~~

2023-10-04 10:32 UTC, jongwooparkk approved these changes

2023-10-04 10:32 UTC, jongwooparkk commented on profile/software/software.md
> +- ~~🐶 권영민~~
마음이 아픕니다 ㅠㅠ 
진짜 마지막이라는 것이 느껴지는 PR입니다.

있는 곳 어디든 항상 즐거운 일들이 가득하기를 바랄께요~

2023-10-04 10:43 UTC, pjs102793 commented
그동안 수고하셨습니다 ㅠㅠ 앞으로 더욱 더 좋은 일이 있기를 바랄게요~ 👍

2023-10-04 10:58 UTC, powerstrong approved these changes
정말 개발자다운 마지막 인사네요 (^^) 함께하는 동안 저도 많이 배웠습니다. 수고하셨고 앞으로도 건승하시길 바랍니다 영민님!

2023-10-04 11:21 UTC, gayounghan requested changes
안돼 못보내 어디가요

2023-10-04 11:26 UTC, bxtbold approved these changes
The only PR I didn't want to approve 😞. Best of luck to your future endeavors.

2023-10-04 11:28 UTC, honeybadger78 commented
자 여러분 몰카였습니다 :) 영민님 내일 10시까지 출근하세요

2023-10-06 07:37 UTC, taeyeonggim approved these changes
비록 영민님은 안 계시지만, 선물해주신 Github는 영원히 저희 곁에 있을겁니다. :sob: 
어딜 가시든 좋은일만 가득하시길 바라겠습니다. :smile:

2023-10-06 07:39 UTC, merged