49 플라이퍼 명단 최신화
PLAIF-dev/.github pull request #50
Opened 2024-05-20 10:54 UTC by powerstrong

플라잎 대문 페이지를 최신화했습니다.

2024-05-20 23:26 UTC, gunjae-yoon commented on profile/ml/ml.md
> +- [🐺 이지훈](/profile/ml/members/jihun.md)
지훈님 Motion 팀으로 소속이 변경되신거 아니었나요?
아직 공식적으로 인사이동이 된 것은 아닌건가...

2024-05-20 23:29 UTC, powerstrong commented on profile/ml/ml.md
> +- [🐺 이지훈](/profile/ml/members/jihun.md)
네 ㅋㅋ 발령은 아직입니다. 비전태영님도 참고로 이번주까지 근무 예정이라 이후에도 한번 정리할께요

2024-05-20 23:31 UTC, gunjae-yoon approved these changes
LGTM

2024-05-21 00:00 UTC, gayounghan requested changes
와우, 한 번 정리가 필요하겠다 싶긴 했는데..
진짜 고생하셨습니다!
하지만 approve는 안돼요.🤫

2024-05-21 00:00 UTC, gayounghan commented on profile/vision/vision.md
> +- [💪 한가영](/profile/vision/members/gayoung.md)
다 동물인 것 같은데, 저는 어쩌다가 이런......
통일된 느낌을 위해 아래와 같은 이모지는 어떨까요??🥺
🦄 🐴 🐼 🐬

2024-05-21 00:12 UTC, powerstrong commented on profile/vision/vision.md
> +- [💪 한가영](/profile/vision/members/gayoung.md)
강하지만 귀여운 팬더곰으로 변경해드렸습니다 😊

2024-05-21 00:13 UTC, gunjae-yoon commented on profile/vision/vision.md
> +- [💪 한가영](/profile/vision/members/gayoung.md)
가장 강려크해 보이는 :mammoth: 추천드립니다.

2024-05-21 00:21 UTC, gayounghan commented on profile/vision/vision.md
> +- [💪 한가영](/profile/vision/members/gayoung.md)
@gunjae-yoon ㅋㅋㅋ 안보이네요ㅋㅋㅋㅋ

2024-05-21 00:22 UTC, gayounghan approved these changes
Approve입니다~🤣

2024-05-21 01:16 UTC, merged