배트님 이모지 변경 및 진균 프로필을 추가
PLAIF-dev/.github pull request #60
Opened 2024-07-12 01:00 UTC by JinGyunJeong

배트님 이모지 변경 및 제(정진균) 프로필을 추가하였습니다

2024-07-12 01:08 UTC, powerstrong requested changes
환영합니다 진균님 ㅎㅎㅎ

2024-07-12 01:08 UTC, powerstrong commented on profile/motion/members/jingyun.md
> +
잘생긴 진균님을 알아볼 수 있게 멋진 사진도 추가 부탁드립니닷

2024-07-12 01:09 UTC, JinGyunJeong commented on profile/motion/members/jingyun.md
> +
아앗.. 알겠습니다

2024-07-12 01:10 UTC, gunjae-yoon commented on profile/motion/members/jingyun.md
> +
@JinGyunJeong 어허... 이미지 안 넣으시면 강제로 이런거로 박아드릴 수도 있습니다.
![image](https://github.com/user-attachments/assets/93d7a61e-845c-4bef-b9c5-3dd5c00dd040)

2024-07-12 01:40 UTC, JinGyunJeong commented on profile/motion/members/jingyun.md
> +
마땅한 사진이 없어 그냥 비슷하게 또 찍어버렸습니다,,

2024-07-12 01:49 UTC, SA-Baitham commented on profile/motion/members/jingyun.md
> +미래 아이언 맨 개발에 코드 한 줄 넣고 싶은 정진균입니다.
정진균 님, 아이언 맨 개발에 코드 한 줄 넣으시면 토니 스타크가 긴장하겠네요! ㅋㅋ

2024-07-12 02:06 UTC, powerstrong commented on profile/motion/members/jingyun.md
> +
최곱니다! 이 수정 제안은 Resolve 하겠습니다 ㅎㅎ

2024-07-12 02:07 UTC, powerstrong approved these changes
plaif-dev 정식 개발자가 되신 것을 축하드립니다 😄

2024-07-12 02:09 UTC, eforgacs approved these changes
Very nice! Welcome aboard :)

2024-07-12 02:29 UTC, BlindedShooter commented
환영합니다 진균님! 아이언 맨 반드시 함께 개발하시죠...! :+1:

2024-07-12 02:30 UTC, BlindedShooter approved these changes
환영합니다 진균님! 아이언 맨 반드시 함께 개발하시죠...! :+1:

2024-07-12 02:30 UTC, BlindedShooter commented on profile/motion/motion.md
> +- [🦇 배트볼드](/profile/motion/members/batbold.md)
:smile: :smile:

2024-07-12 02:34 UTC, eforgacs commented on profile/motion/motion.md
> +- [🦇 배트볼드](/profile/motion/members/batbold.md)
Hah. This makes perfect sense, why have we not done this until now?

2024-07-12 02:38 UTC, powerstrong commented on profile/motion/motion.md
> +- [🦇 배트볼드](/profile/motion/members/batbold.md)
위에 웃고 계신 @BlindedShooter 님, 모션팀 멤버가 한명 비는 것 같지 않나요?

2024-07-12 03:07 UTC, ssongzoe commented on profile/motion/motion.md
> +- [🦇 배트볼드](/profile/motion/members/batbold.md)
수정하는 김에 지훈님 path도 옮기면 어떠십니까~~ @BlindedShooter

2024-07-12 05:01 UTC, BlindedShooter commented on profile/motion/motion.md
> +- [🦇 배트볼드](/profile/motion/members/batbold.md)
:sweat_smile:

2024-07-12 07:10 UTC, bxtbold approved these changes
LGTM

2024-07-12 07:10 UTC, bxtbold commented on profile/motion/motion.md
> +- [🦇 배트볼드](/profile/motion/members/batbold.md)
LGTM 🦇

2024-07-15 01:21 UTC, gayounghan approved these changes
환영해요!
보드게임 할 때 조용하지만 진균님의 똑똑함을 봤어요.
근데, 한 줄만?????????🤨 좀 더 써요!

2024-07-15 01:41 UTC, jongwooparkk approved these changes
환영합니다~ 
앞으로도 잘 부탁 드려요~

2024-07-15 01:41 UTC, jongwooparkk commented on profile/motion/motion.md
> +- [🦇 배트볼드](/profile/motion/members/batbold.md)
근데 왜 새 이모지로 바꾼거에요..? 새처럼 날아서 골을 넣어라?

2024-07-15 03:18 UTC, jongwooparkk commented on profile/motion/motion.md
> +- [🦇 배트볼드](/profile/motion/members/batbold.md)
박쥐였군요.... 미안합니다............

2024-07-15 03:20 UTC, JinGyunJeong commented on profile/motion/motion.md
> +- [🦇 배트볼드](/profile/motion/members/batbold.md)
배트님이 박쥐로해달라고 하셨습니다 ㅋㅋ

2024-07-15 03:26 UTC, merged

2024-07-15 03:26 UTC, JinGyunJeong commented
잘 부탁드립니다~

2024-07-15 03:27 UTC, gayounghan commented on profile/motion/motion.md
> +- [🦇 배트볼드](/profile/motion/members/batbold.md)
@jongwooparkk 🤣🤣🤣🤣🤣🤣 근데 깃헙에서 쓰는 이모지가 좀 알아보기 힘든 것 같아요....

2024-07-15 04:58 UTC, jongwooparkk commented on profile/motion/motion.md
> +- [🦇 배트볼드](/profile/motion/members/batbold.md)
@gayounghan 그쵸~?? 저만 그런거 아니군요~ ㅎㅎㅎ